var isNodeJS=!1;try{isNodeJS="undefined"!==typeof module&&"undefined"!==typeof module.exports&&"undefined"!==process&&"undefined"!==global}catch(d){}
(function(n){function t(a){var c=a.lastIndexOf("/");a=a.substr(0,c);return""==a?a:a+"/"}function v(a,c){if(":"==a.charAt(0))return p.repoBase+"?v="+p.version+"&f="+a.substr(1);if("/"===a.charAt(0)||"http:"===a.substr(0,5))return a;if("~/"===a.substr(0,2))return a.substr(2);if("undefined"!==typeof p.paths){var b=a.indexOf("/"),e=a.substr(0,b),e=p.paths[e];if("undefined"!==typeof e)return k.endsWith(e,"/")||(e+="/"),e+a.substr(b+1)}if("undefined"===typeof c)return a;b=a.split("/");e=c.split("/");for(""==
e[e.length-1]&&e.pop();0<b.length&&".."==b[0];)b.shift(),e.pop();return e.join("/")+(0<e.length?"/":"")+b.join("/")}function w(){return"undefined"===typeof h.base&&null!==document.currentScript?t(document.currentScript.src):h.base}function y(a,c){var b=t(c),e={exports:{__undefined:!0}},f=h.latestClass;delete h.latestClass;var g=h.base;h.base=b;var l=h.globalScope;h.globalScope={};b=!0;try{eval(a)}catch(k){throw e=k.stack.match(/>:([0-9]*):/),e=0<e.length?" on line "+e.pop():"",k.message=k.message+
" in file "+c+e,k;}for(var m in h.globalScope)"!"===m[0]?n[m.substr(1)]=h.globalScope[m]:eval("var "+m+"=pkgEnv.globalScope['"+m+"']");h.globalScope=l;m=h.latestClass;h.latestClass=f;h.base=g;b=e.exports;delete e.exports;return"undefined"===typeof b||b.__undefined?0<Object.keys(e).length?e:m:b}function r(a){var c=this;if("undefined"!==typeof this.deepProperties){for(var b in this.deepProperties)this[b]=JSON.parse(this.deepProperties[b]);delete this.deepProperties}b=k.mixin({},this["private"]||{});
z.addPrivateScope(this,b);var e={},f={};this.trigger=function(a,b,c){if(a=e[a])for(var f in a)a[f].call(this,b,c)};this.on=function(a,b){if("change:"===a.substr(0,7)){var g=a.substr(7);"undefined"===typeof f[g]&&(f[g]=this[g]);Object.defineProperty(this,g,{enumerable:!0,configurable:!0,get:function(){return f[g]},set:function(b){f[g]=b;c.trigger(a,b,function(a){f[g]=a});return b}})}e[a]?e[a].push(b):e[a]=[b]};a||(a={});!0!=this.domless&&(b=n.jQuery||n.$,a.el?a.el instanceof b?(this.$el=a.el,this.el=
a.el[0]):"undefined"!==typeof b&&(this.$el=$(a.el),this.el=a.el):"undefined"!==typeof document&&(this.el=document.createElement(this.tagName?this.tagName:"div"),"undefined"!==typeof b&&(this.$el=b(this.el))),"undefined"!==typeof this.className&&(this.el.className=this.className),"undefined"!==typeof this.id&&(this.el.id=this.id));if("undefined"!==typeof this.events){var g=this.el,h=this.$el;if(!h)var p=!1,p=document.body.webkitMatchesSelector?"webkitMatchesSelector":document.body.mozMatchesSelector?
"mozMatchesSelector":!1;var m=this.events,q;for(q in m)(function(){var a=m[q];if("string"==typeof a){var b=c[a];if(b)a=b;else{console.log('TRICKS: the event method "'+a+'" was not found on the trick',c);return}}var e=q.indexOf(" ");if(-1==e)b=q;else var b=q.substr(0,e),f=q.substr(e+1);if(h)h.on(b,f,function(b){a.call(c,b,this)});else g.addEventListener(b,function(b){if(p)for(var h=b.target,k=0;50>k;k++)if(h)if(-1==e||h[p](f)){b.currentTarget=h;a.call(c,b,h);break}else{if(h=h.parentNode,h===g)break}else break})})()}}
function s(a,c){if(a&&a["extends"]){var b=a["extends"];delete a["extends"];if(b instanceof Array&&0<b.length){var e=b.shift();"string"===typeof e&&(e=getModule(k.endsWith(e,".js")?e:e+".js"));return e.extend(a,b)}"string"===typeof b&&(b=getModule(k.endsWith(b,".js")?b:b+".js"));return b.extend(a)}b=function(b){r.call(this,b);"undefined"!==typeof a&&a.singleton||"function"!==typeof this.init||this.init.apply(this,arguments)};b.extend=A;if(c)return b;b.prototype=Object.create(r.prototype);return x(b,
a)}function B(a){var c;return function(b){if(c)return c;c=new a(b);"function"===typeof c.init&&c.init.apply(c,arguments);return c}}function x(a,c){var b,e,f,g;if("undefined"===typeof c)return a;if("undefined"!==typeof c.defaults){var l=c.defaults;delete c.defaults}"undefined"!==typeof a.prototype["private"]&&"undefined"!==typeof c["private"]&&k.mixin_passive(c["private"],a.prototype["private"]);k.mixin(a.prototype,c);if("undefined"!==typeof l){g="undefined"===typeof a.prototype.deepProperties?a.prototype.deepProperties=
{}:a.prototype.deepProperties;for(f in l)l[f]instanceof Object?g[f]=JSON.stringify(l[f]):a.prototype[f]=l[f];k.mixin(a.prototype,l)}if("undefined"!==typeof c.requires){var l="string"===typeof c.requires?[c.requires]:c.requires,p;for(p in l){g=l[p];b=g.indexOf(" ");e=-1==b?g:g.substr(0,b);g=g.substr(b+1);f="js";var m=e.length;k.endsWith(e,".js")?e=e.substr(0,m-3):k.endsWith(e,".hbs")?(e=e.substr(0,m-4),f="hbs"):k.endsWith(e,".handlebars")&&(e=e.substr(0,m-11),f="handlebars");var q=g.indexOf("."),m=
void 0;-1==b?(k.endsWith(g,f)&&(g=g.substr(0,g.length-f.length-1)),g=g.substr(g.lastIndexOf("/")+1)):-1<q?(m=g.substr(0,q),g=g.substr(q+1)):m=g;b=e;e=m;g=":"===g.charAt(0)?g.substr(1):g;f=getModule(b+"."+f);"this"===e?a.prototype[g]=f:"window"===e||h.globalScope===n?n[g]=f:(h.globalScope["!"+g]=n[g],n[g]=f,h.globalScope[g]=f)}delete c.requires}c.singleton&&(a=B(a));return h.latestClass=a}function A(a,c){var b=s(a,!0);C(b,this);if("undefined"!==typeof c)for(var e=0;e<c.length;e++){var f=c[e];"string"===
typeof f&&(f=getModule(k.endsWith(f,".js")?f:f+".js"));k.mixin_passive(b.prototype,f);if("undefined"!==typeof f.prototype.defaults){var f="undefined"===typeof b.prototype.deepProperties?b.prototype.deepProperties={}:b.prototype.deepProperties,g;for(g in defaults)defaults[g]instanceof Object&&"undefined"===typeof f[g]&&(f[g]=JSON.stringify(defaults[g]))}}return x(b,a)}var p={version:1,repoBase:"http://timber.io/repo/"},k={mixin:function(a,c){if("function"==typeof c&&"object"==typeof c.prototype)return k.mixin(a,
c.prototype);for(var b in c)a[b]=c[b];return a},mixin_passive:function(a,c){if("function"==typeof c&&"object"==typeof c.prototype)return k.mixin_passive(a,c.prototype);for(var b in c)"undefined"===typeof a[b]&&(a[b]=c[b]);return a},endsWith:function(a,c){return a.substr(a.length-c.length)===c}};Function.prototype.bind=function(a){var c=this;return function(){return c.apply(a,arguments)}};var h={cachedFiles:{},globalScope:n};s.addPath=function(a,c){var b=v(c,w());"undefined"===typeof p.paths&&(p.paths=
{});p.paths[a]=b};if(isNodeJS){h.base=t(module.parent.filename);var D=function(a,c){var b=h.httpsync;if("undefined"===typeof b)try{b=h.httpsync=require("httpsync")}catch(e){throw"\n\n\n\n===========================================================\n\nTimber requires the package httpsync, run the command: \n\n\tnpm -g install httpsync\n\n===========================================================\n\n\n\n";}var b=b.get(a).end().data.toString(),f={console:console,setTimeout:setTimeout,clearTimeout:clearTimeout,
require:require,process:process,Buffer:Buffer,timber:timber,exports:exports,module:{exports:{__undefined:!0}}};c=t(a);f.getModule=function(a){return h.getModule_real(a,c)};require("vm").runInNewContext(b,f,a);return"undefined"===typeof f.module.exports||f.module.exports.__undefined?f.module:f.module.exports}}h.getModule_real=function(a,c){var b=v(a,c),e=a.substr(a.lastIndexOf("/")+1);if("undefined"!==typeof h.cachedFiles[e])return h.cachedFiles[e];if(isNodeJS){var f=h.base,g=h.latestClass;h.base=
t(b);var l;if("http:"===b.substr(0,5))l=D(b,c);else try{l=require(b)}catch(n){b=a.lastIndexOf("."),-1<b&&(a=a.substr(0,b)),l=require(a)}"object"===typeof l&&0===Object.keys(l).length&&(l=h.latestClass);h.latestClass=g;h.base=f;return h.cachedFiles[e]=l}f=new XMLHttpRequest;f.open("GET",b,!1);f.send("");return k.endsWith(b,".hbs")||k.endsWith(b,".handlebars")?(b=h.getModule_real(":handlebars.js",""),h.cachedFiles[e]=b.compile(f.responseText)):h.cachedFiles[e]=y(f.responseText,b)};n.getModule=function(a){return h.getModule_real(a,
w())};"undefined"===typeof n.require&&(n.require=n.getModule);var E=function(){var a={},c=this._super,b;for(b in c)"function"==typeof c[b]&&"constructor"!=b&&(a[b]=u(c[b],this,c._super));a.constructor=u(c.constructor,this,c._super);return a},u=function(a,c,b){return function(){".super";c=c?c:this;var e=c._super;c._super=b;var f=a.apply(c,arguments);c._super=e;return f}},C=function(a,c){a.prototype=Object.create(c.prototype);a.prototype._super=c.prototype;Object.defineProperty(a.prototype,"super",
{enumerable:!1,configurable:!0,set:function(a){},get:E});var b=/\.super/,e;for(e in c.prototype)"function"==typeof c.prototype[e]&&b.test(c.prototype[e].toString())&&(a.prototype[e]=u(c.prototype[e],void 0,c.prototype._super));a.prototype.constructor=a},z={cache:{},hasPrivateScope:function(a){var c=a.toString();a=a.name+":"+a.length+":"+c.length;return"undefined"!==typeof this.cache[a]?this.cache[a]:this.cache[a]=-1<c.indexOf("this.private")},addPrivateScope:function(a,c){"undefined"===typeof c&&
(c={});var b=this;Object.defineProperty(a,"private",{enumerable:!0,configurable:!0,set:function(a){},get:function(){return b.hasPrivateScope(arguments.callee.caller)?c:void 0}})}};r.prototype.extend=function(){for(var a=0;a<arguments.length;a++)k.mixin(Object.getPrototypeOf(this),arguments[a])};r.prototype.get=function(a){return this[a]};r.prototype.set=function(a,c){this[a]=c};r.prototype.delay=function(a){var c={},b=this,e=function(c){return function(){setTimeout(function(){b[c].apply(b,arguments)},
a);return b}},f;for(f in this)"function"===typeof this[f]&&(c[f]=e(f));return c};s.config=function(a){k.mixin(p,a)};n.timber=s;"undefined"!==typeof module&&"undefined"!==typeof module.exports&&(module.exports=s);"function"===typeof n.define&&"function"===typeof n.define.amd&&n.define("timber",[],function(){return s})})(isNodeJS?global:window);
