var isNodeJS=!1;try{isNodeJS="undefined"!==typeof module&&"undefined"!==typeof module.exports&&"undefined"!==process&&"undefined"!==global}catch(d){}
(function(l){function r(a){var c=a.lastIndexOf("/");a=a.substr(0,c);return""==a?a:a+"/"}function w(a,c){if(":"==a.charAt(0))return u.repoBase+"?v="+u.version+"&f="+a.substr(1);if("./"==a.substr(0,2))return a.substr(2);if("/"==a.charAt(0)||"http:"==a.substr(0,5)||"undefined"===typeof c)return a;var b=a.split("/"),f=c.split("/");for(""==f[f.length-1]&&f.pop();0<b.length&&".."==b[0];)b.shift(),f.pop();return f.join("/")+(0<f.length?"/":"")+b.join("/")}function q(a){var c=this;if("undefined"!==typeof this.deepProperties){for(var b in this.deepProperties)this[b]=
JSON.parse(this.deepProperties[b]);delete this.deepProperties}b=k.mixin({},this["private"]||{});x.addPrivateScope(this,b);var f={},e={};this.trigger=function(a,c,b){if(a=f[a])for(var e in a)a[e].call(this,c,b)};this.on=function(a,b){if("change:"===a.substr(0,7)){var g=a.substr(7);"undefined"===typeof e[g]&&(e[g]=this[g]);Object.defineProperty(this,g,{enumerable:!0,configurable:!0,get:function(){return e[g]},set:function(b){e[g]=b;c.trigger(a,b,function(a){e[g]=a});return b}})}f[a]?f[a].push(b):f[a]=
[b]};a||(a={});!0!=this.domless&&(a.el?a.el instanceof jQuery?(this.$el=a.el,this.el=a.el[0]):"undefined"!==typeof jQuery&&(this.$el=$(a.el),this.el=a.el):"undefined"!==typeof document&&(this.el=document.createElement(this.tagName?this.tagName:"div"),"undefined"!==typeof jQuery&&(this.$el=jQuery(this.el))),"undefined"!==typeof this.className&&(this.el.className=this.className),"undefined"!==typeof this.id&&(this.el.id=this.id));if("undefined"!==typeof this.events){var g=this.el,h=this.$el;if(!h)var l=
!1,l=document.body.webkitMatchesSelector?"webkitMatchesSelector":document.body.mozMatchesSelector?"mozMatchesSelector":!1;var n=this.events,p;for(p in n)(function(){var a=n[p];if("string"==typeof a){var b=c[a];if(b)a=b;else{console.log('TRICKS: the event method "'+a+'" was not found on the trick',c);return}}var e=p.indexOf(" ");if(-1==e)b=p;else var b=p.substr(0,e),f=p.substr(e+1);if(h)h.on(b,f,function(b){a.call(c,b,this)});else g.addEventListener(b,function(b){if(l)for(var h=b.target,k=0;50>k;k++)if(h)if(-1==
e||h[l](f)){b.currentTarget=h;a.call(c,b,h);break}else{if(h=h.parentNode,h===g)break}else break})})()}}function s(a,c){if(a&&a["extends"]){var b=a["extends"];delete a["extends"];if(b instanceof Array&&0<b.length){var f=b.shift();"string"===typeof f&&(f=getModule(k.endsWith(f,".js")?f:f+".js"));return f.extend(a,b)}"string"===typeof b&&(b=getModule(k.endsWith(b,".js")?b:b+".js"));return b.extend(a)}b=function(b){q.call(this,b);"undefined"!==typeof a&&a.singleton||"function"!==typeof this.init||this.init.apply(this,
arguments)};b.extend=y;if(c)return b;b.prototype=Object.create(q.prototype);return v(b,a)}function z(a){var c;return function(b){if(c)return c;c=new a(b);"function"===typeof c.init&&c.init.apply(c,arguments);return c}}function v(a,c){var b,f,e,g;if("undefined"===typeof c)return a;if("undefined"!==typeof c.defaults){var m=c.defaults;delete c.defaults}"undefined"!==typeof a.prototype["private"]&&"undefined"!==typeof c["private"]&&k.mixin_passive(c["private"],a.prototype["private"]);k.mixin(a.prototype,
c);if("undefined"!==typeof m){g="undefined"===typeof a.prototype.deepProperties?a.prototype.deepProperties={}:a.prototype.deepProperties;for(e in m)m[e]instanceof Object?g[e]=JSON.stringify(m[e]):a.prototype[e]=m[e];k.mixin(a.prototype,m)}if("undefined"!==typeof c.requires){var m="string"===typeof c.requires?[c.requires]:c.requires,l;for(l in m){g=m[l];b=g.indexOf(" ");f=-1==b?g:g.substr(0,b);g=g.substr(b+1);e="js";var n=f.length;k.endsWith(f,".js")?f=f.substr(0,n-3):k.endsWith(f,".hbs")?(f=f.substr(0,
n-4),e="hbs"):k.endsWith(f,".handlebars")&&(f=f.substr(0,n-11),e="handlebars");var p=g.indexOf("."),n=void 0;-1==b?(k.endsWith(g,e)&&(g=g.substr(0,g.length-e.length-1)),g=g.substr(g.lastIndexOf("/")+1)):-1<p?(n=g.substr(0,p),g=g.substr(p+1)):n=g;b=f;f=n;g=":"===g.charAt(0)?g.substr(1):g;e=getModule(b+"."+e);"this"==f?a.prototype[g]=e:"undefined"===typeof h.globalScope[g]&&(h.globalScope[g]=e)}delete c.requires}c.singleton&&(a=z(a));return h.latestClass=a}function y(a,c){var b=s(a,!0);A(b,this);if("undefined"!==
typeof c)for(var f=0;f<c.length;f++){var e=c[f];"string"===typeof e&&(e=getModule(k.endsWith(e,".js")?e:e+".js"));k.mixin_passive(b.prototype,e);if("undefined"!==typeof e.prototype.defaults){var e="undefined"===typeof b.prototype.deepProperties?b.prototype.deepProperties={}:b.prototype.deepProperties,g;for(g in defaults)defaults[g]instanceof Object&&"undefined"===typeof e[g]&&(e[g]=JSON.stringify(defaults[g]))}}return v(b,a)}var u={version:1,repoBase:"http://timber.io/repo/"},k={mixin:function(a,
c){if("function"==typeof c&&"object"==typeof c.prototype)return k.mixin(a,c.prototype);for(var b in c)a[b]=c[b];return a},mixin_passive:function(a,c){if("function"==typeof c&&"object"==typeof c.prototype)return k.mixin_passive(a,c.prototype);for(var b in c)"undefined"===typeof a[b]&&(a[b]=c[b]);return a},endsWith:function(a,c){return a.substr(a.length-c.length)===c}};Function.prototype.bind=function(a){var c=this;return function(){return c.apply(a,arguments)}};var h={cachedFiles:{},globalScope:l};
if(isNodeJS){h.base=r(module.parent.filename);var B=function(a,c){var b=h.httpsync;if("undefined"===typeof b)try{b=h.httpsync=require("httpsync")}catch(f){throw"\n\n\n\n===========================================================\n\nTimber requires the package httpsync, run the command: \n\n\tnpm -g install httpsync\n\n===========================================================\n\n\n\n";}var b=b.get(a).end().data.toString(),e={console:console,setTimeout:setTimeout,clearTimeout:clearTimeout,require:require,
process:process,Buffer:Buffer,timber:timber,exports:exports,module:{exports:{__undefined:!0}}};c=r(a);e.getModule=function(a){return h.getModule_real(a,c)};require("vm").runInNewContext(b,e,a);return"undefined"===typeof e.module.exports||e.module.exports.__undefined?e.module:e.module.exports}}h.getModule_real=function(a,c){var b=w(a,c),f=a.substr(a.lastIndexOf("/")+1);if("undefined"!==typeof h.cachedFiles[f])return h.cachedFiles[f];if(isNodeJS){var e=h.base,g=h.latestClass;h.base=r(b);var m;if("http:"===
b.substr(0,5))m=B(b,c);else try{m=require(b)}catch(l){b=a.lastIndexOf("."),-1<b&&(a=a.substr(0,b)),m=require(a)}"object"===typeof m&&0===Object.keys(m).length&&(m=h.latestClass);h.latestClass=g;h.base=e;return h.cachedFiles[f]=m}e=new XMLHttpRequest;e.open("GET",b,!1);e.send("");if(k.endsWith(b,".hbs")||k.endsWith(b,".handlebars"))return b=h.getModule_real(":handlebars.js",""),h.cachedFiles[f]=b.compile(e.responseText);c=r(b);b='window.__timberRequire = function(pkgEnv) {                    \t\t\t\t\tfunction getModule(filename) {\t\t\t\t\t\treturn pkgEnv.getModule_real(filename, "'+
c+'");\t\t\t\t\t}                    \t\t\t\t\tvar module = { exports: { __undefined: true } };                    \t\t\t\t\tvar prevLatestClass = pkgEnv.latestClass;\t\t\t\t\tdelete pkgEnv.latestClass;\t\t\t\t\tvar prevBase = pkgEnv.base;                    /*var prevGlobalScope = pkgEnv.globalScope;*/                    /*pkgEnv.globalScope = {};*/                    pkgEnv.base = "'+c+'";                    \t\t\t\t\t'+e.responseText+';                    \t\t\t\t\tvar thisClass = pkgEnv.latestClass;\t\t\t\t\tpkgEnv.latestClass = prevLatestClass;\t\t\t\t\tpkgEnv.base = prevBase;                                        /*for(var name in pkgEnv.globalScope)                        eval("var " + name + "=" + "pkgEnv.globalScope[\'" + name + "\']");                    pkgEnv.globalScope = prevGlobalScope;*/                    \t\t\t\t\tvar exports = module.exports;\t\t\t\t\tdelete module.exports;\t\t\t\t\tif(typeof exports !== "undefined" && !exports.__undefined) {\t\t\t\t\t\treturn exports;\t\t\t\t\t}else if(Object.keys(module).length > 0) {\t\t\t\t\t\treturn module;\t\t\t\t\t}else{\t\t\t\t\t\treturn thisClass;\t\t\t\t\t}\t\t\t\t}';
e=document.createElement("script");e.type="text/javascript";e.text=b;document.getElementsByTagName("head")[0].appendChild(e);return h.cachedFiles[f]=window.__timberRequire(h)};l.getModule=function(a){return h.getModule_real(a,"undefined"===typeof h.base?r(document.currentScript.src):h.base)};"undefined"===typeof l.require&&(l.require=l.getModule);var C=function(){var a={},c=this._super,b;for(b in c)"function"==typeof c[b]&&"constructor"!=b&&(a[b]=t(c[b],this,c._super));a.constructor=t(c.constructor,
this,c._super);return a},t=function(a,c,b){return function(){".super";c=c?c:this;var f=c._super;c._super=b;var e=a.apply(c,arguments);c._super=f;return e}},A=function(a,c){a.prototype=Object.create(c.prototype);a.prototype._super=c.prototype;Object.defineProperty(a.prototype,"super",{enumerable:!1,configurable:!0,set:function(a){},get:C});var b=/\.super/,f;for(f in c.prototype)"function"==typeof c.prototype[f]&&b.test(c.prototype[f].toString())&&(a.prototype[f]=t(c.prototype[f],void 0,c.prototype._super));
a.prototype.constructor=a},x={cache:{},hasPrivateScope:function(a){var c=a.toString();a=a.name+":"+a.length+":"+c.length;return"undefined"!==typeof this.cache[a]?this.cache[a]:this.cache[a]=-1<c.indexOf("this.private")},addPrivateScope:function(a,c){"undefined"===typeof c&&(c={});var b=this;Object.defineProperty(a,"private",{enumerable:!0,configurable:!0,set:function(a){},get:function(){return b.hasPrivateScope(arguments.callee.caller)?c:void 0}})}};q.prototype.extend=function(){for(var a=0;a<arguments.length;a++)k.mixin(Object.getPrototypeOf(this),
arguments[a])};q.prototype.get=function(a){return this[a]};q.prototype.set=function(a,c){this[a]=c};q.prototype.delay=function(a){var c={},b=this,f=function(c){return function(){setTimeout(function(){b[c].apply(b,arguments)},a);return b}},e;for(e in this)"function"===typeof this[e]&&(c[e]=f(e));return c};l.timber=s;"undefined"!==typeof module&&"undefined"!==typeof module.exports&&(module.exports=s);"function"===typeof l.define&&"function"===typeof l.define.amd&&l.define("timber",[],function(){return s})})(isNodeJS?
global:window);
